name: code checks

on:
  pull_request:
  push:
    branches:
    - 'master'
    - 'feature/**'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  code_checks:

    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04, windows-latest ]
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    environment: ci

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint pytest
          pip install -r requirements.txt
      - name: Lint with pylint
        env:
          PYTHONPATH: ${GITHUB_WORKSPACE}
        run: |
          python -m pylint *.py tests/
      - name: Check formatting with black
        run: |
          python -m black --check *.py tests/
      - name: Test with pytest
        run: |
          python -m pytest
        env:
          HEMS_LOOKOUT_FCM_AUTH_STR: ${{ secrets.HEMS_LOOKOUT_FCM_AUTH_STR }}
